name: Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun build
      
      - name: Push result to main repository
        run: bun ./.github/publish.cjs
        env:
          MAIN_PAT: ${{ secrets.MAIN_PAT }}

